export const CATEGORIES = [
  {id:'desayuno', name:'Desayuno', color:'#D98E04'},
  {id:'almuerzo', name:'Almuerzo', color:'#2F6B4F'},
  {id:'cena',     name:'Cena',     color:'#6B4226'},
  {id:'postre',   name:'Postre',   color:'#B5548C'},
  {id:'bebida',   name:'Bebida',   color:'#2E7D9A'},
];
export const catColor = id => (CATEGORIES.find(c=>c.id===id)||{}).color || '#2F6B4F';
export const catName  = id => (CATEGORIES.find(c=>c.id===id)||{}).name || id;

export const RECIPES = [
  {id:'panqueques', name:'Panqueques clásicos', category:'desayuno', time:20, difficulty:'Fácil', servings:2,
    macros:{kcal:320, prot:9, carbs:48, fat:10},
    ingredients:['2 tazas de harina','2 huevos','1 ½ tazas de leche','2 cdas de azúcar','1 cdta de polvo de hornear'],
    steps:[
      {text:'Mezcla la harina, el azúcar y el polvo de hornear en un bowl grande.', seconds:0},
      {text:'Agrega los huevos y la leche. Bate hasta obtener una mezcla homogénea.', seconds:0},
      {text:'Calienta un sartén antiadherente a fuego medio.', seconds:60},
      {text:'Vierte ¼ de taza de mezcla y cocina hasta que aparezcan burbujas.', seconds:90},
      {text:'Voltea el panqueque y cocina el otro lado hasta dorar.', seconds:60},
      {text:'Sirve con miel o fruta al gusto. ¡Buen provecho!', seconds:0},
    ]},
  {id:'tostadas', name:'Tostadas con palta', category:'desayuno', time:10, difficulty:'Fácil', servings:1,
    macros:{kcal:240, prot:6, carbs:26, fat:13},
    ingredients:['2 rebanadas de pan integral','1 palta madura','Sal y limón al gusto'],
    steps:[
      {text:'Tuesta las rebanadas de pan hasta que estén doradas.', seconds:120},
      {text:'Machaca la palta con un tenedor en un bowl.', seconds:0},
      {text:'Sazona con sal y unas gotas de limón.', seconds:0},
      {text:'Unta la palta sobre las tostadas y sirve.', seconds:0},
    ]},
  {id:'cesar', name:'Ensalada César', category:'almuerzo', time:15, difficulty:'Fácil', servings:2,
    macros:{kcal:290, prot:12, carbs:14, fat:20},
    ingredients:['1 lechuga romana','Crutones','Queso parmesano','Aderezo César','Pechuga de pollo (opcional)'],
    steps:[
      {text:'Lava y corta la lechuga romana en trozos medianos.', seconds:0},
      {text:'Agrega los crutones y el queso parmesano rallado.', seconds:0},
      {text:'Incorpora el aderezo César y mezcla bien.', seconds:0},
      {text:'Sirve fría, con pollo a la plancha si lo deseas.', seconds:0},
    ]},
  {id:'lomo', name:'Lomo saltado', category:'almuerzo', time:35, difficulty:'Media', servings:3,
    macros:{kcal:480, prot:28, carbs:42, fat:22},
    ingredients:['500g de lomo en tiras','2 tomates','1 cebolla roja','Papas fritas','Sillao y vinagre'],
    steps:[
      {text:'Corta la carne en tiras y sazona con sal y pimienta.', seconds:0},
      {text:'Sella la carne en el wok a fuego alto por 2 minutos.', seconds:120},
      {text:'Agrega la cebolla y el tomate, saltea brevemente.', seconds:90},
      {text:'Incorpora sillao y vinagre, mezcla rápido a fuego alto.', seconds:60},
      {text:'Sirve con papas fritas y arroz.', seconds:0},
    ]},
  {id:'sopa', name:'Sopa de verduras', category:'cena', time:40, difficulty:'Fácil', servings:4,
    macros:{kcal:180, prot:6, carbs:24, fat:5},
    ingredients:['Zanahoria','Apio','Zapallo','Papa','Caldo de verduras'],
    steps:[
      {text:'Corta todas las verduras en cubos medianos.', seconds:0},
      {text:'Sofríe la cebolla y el apio por 3 minutos.', seconds:180},
      {text:'Agrega el resto de verduras y el caldo.', seconds:0},
      {text:'Cocina a fuego medio hasta que las verduras estén suaves.', seconds:900},
      {text:'Sazona y sirve caliente.', seconds:0},
    ]},
  {id:'pesto', name:'Pasta al pesto', category:'cena', time:25, difficulty:'Media', servings:2,
    macros:{kcal:410, prot:11, carbs:52, fat:16},
    ingredients:['200g de pasta','Albahaca fresca','Piñones','Ajo','Aceite de oliva','Parmesano'],
    steps:[
      {text:'Hierve agua con sal y cocina la pasta.', seconds:600},
      {text:'Licúa albahaca, piñones, ajo, aceite y parmesano.', seconds:0},
      {text:'Escurre la pasta y mezcla con el pesto.', seconds:0},
      {text:'Sirve con parmesano extra por encima.', seconds:0},
    ]},
  {id:'brownie', name:'Brownie de chocolate', category:'postre', time:45, difficulty:'Media', servings:8,
    macros:{kcal:350, prot:5, carbs:40, fat:19},
    ingredients:['200g chocolate','150g mantequilla','3 huevos','1 taza de azúcar','1 taza de harina'],
    steps:[
      {text:'Derrite el chocolate con la mantequilla a baño maría.', seconds:180},
      {text:'Bate los huevos con el azúcar hasta espumar.', seconds:0},
      {text:'Une ambas mezclas e incorpora la harina con movimientos suaves.', seconds:0},
      {text:'Vierte en un molde y hornea a 180°C.', seconds:1500},
      {text:'Deja enfriar antes de cortar en cuadros.', seconds:0},
    ]},
  {id:'frutas', name:'Ensalada de frutas', category:'postre', time:10, difficulty:'Fácil', servings:2,
    macros:{kcal:140, prot:2, carbs:34, fat:1},
    ingredients:['Manzana','Plátano','Uvas','Naranja','Miel al gusto'],
    steps:[
      {text:'Lava y corta toda la fruta en trozos pequeños.', seconds:0},
      {text:'Mezcla todo en un bowl grande.', seconds:0},
      {text:'Agrega un poco de miel y sirve fría.', seconds:0},
    ]},
  {id:'limonada', name:'Limonada de coco', category:'bebida', time:8, difficulty:'Fácil', servings:2,
    macros:{kcal:120, prot:1, carbs:22, fat:3},
    ingredients:['Jugo de 4 limones','Leche de coco','Azúcar al gusto','Hielo'],
    steps:[
      {text:'Exprime los limones y cuela el jugo.', seconds:0},
      {text:'Licúa el jugo con la leche de coco y el azúcar.', seconds:60},
      {text:'Sirve con hielo bien frío.', seconds:0},
    ]},
  {id:'smoothie', name:'Smoothie de frutos rojos', category:'bebida', time:6, difficulty:'Fácil', servings:1,
    macros:{kcal:160, prot:3, carbs:30, fat:2},
    ingredients:['1 taza de frutos rojos','1 plátano','Yogur natural','Hielo'],
    steps:[
      {text:'Coloca todos los ingredientes en la licuadora.', seconds:0},
      {text:'Licúa hasta obtener una mezcla homogénea.', seconds:45},
      {text:'Sirve de inmediato.', seconds:0},
    ]},
];
